version: "3.9"

services:
  # --- Core infrastructure ---
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/appdata/caddy:/etc/caddy:ro
      - /srv/appdata/caddy/data:/data
      - /srv/appdata/caddy/config:/config
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: --label-enable --cleanup --interval 43200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
      - TZ=${TZ}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # --- Monitoring ---
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - /srv/appdata/uptime-kuma:/app/data
    ports:
      - "3001:3001"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - NTFY_LISTEN_HTTP=:80
    command: ["serve"]
    volumes:
      - /srv/appdata/ntfy/cache:/var/cache/ntfy
      - /srv/appdata/ntfy/config:/etc/ntfy
    ports:
      - "8080:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

  # --- Media stack ---
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /srv/appdata/jellyfin/config:/config
      - /srv/appdata/jellyfin/cache:/cache
      - /srv/media:/data:ro
    ports:
      - "8096:8096"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    volumes:
      - /srv/appdata/jellyseerr:/app/config
    ports:
      - "5055:5055"
    networks:
      - proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  gluetun-qb:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-qb
    restart: unless-stopped
    cap_add: [NET_ADMIN]
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORD_USER}
      - OPENVPN_PASSWORD=${NORD_PASS}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CATEGORIES=${SERVER_CATEGORIES}
      - OPENVPN_PROTOCOL=udp
      - FIREWALL_INPUT_PORTS=8080,6881,8191
    volumes:
      - /srv/appdata/gluetun-qb:/gluetun
    ports:
      - "8082:8080/tcp"
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "8191:8191/tcp"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun-qb"
    depends_on: [gluetun-qb]
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=8080
    volumes:
      - /srv/appdata/qbittorrent:/config
      - /srv/media:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  gluetun-sab:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-sab
    restart: unless-stopped
    cap_add: [NET_ADMIN]
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${NORD_USER}
      - OPENVPN_PASSWORD=${NORD_PASS}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CATEGORIES=${SERVER_CATEGORIES}
      - OPENVPN_PROTOCOL=udp
      - FIREWALL_INPUT_PORTS=8080
    volumes:
      - /srv/appdata/gluetun-sab:/gluetun
    ports:
      - "8083:8080/tcp"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    network_mode: "service:gluetun-sab"
    depends_on: [gluetun-sab]
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /srv/appdata/sabnzbd:/config
      - /srv/media:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    dns: [1.1.1.1, 9.9.9.9]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /srv/appdata/prowlarr:/config
    ports:
      - "9696:9696"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /srv/appdata/sonarr:/config
      - /srv/media:/data
    ports:
      - "8989:8989"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /srv/appdata/radarr:/config
      - /srv/media:/data
    ports:
      - "7878:7878"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /srv/appdata/bazarr:/config
      - /srv/media:/data
    ports:
      - "6767:6767"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    network_mode: "service:gluetun-qb"
    depends_on: [gluetun-qb]
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    ports:
      - "8191:8191"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy:
    name: proxy
    driver: bridge
