version: "3.9"

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../caddy:/etc/caddy:ro
      - ../caddy/data:/data
      - ../caddy/config:/config
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: --label-enable --cleanup --interval 43200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Amsterdam

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
      - TZ=Europe/Amsterdam
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

# --- Monitoring stack ---

  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ../uptime-kuma:/app/data
    ports:
      - "3001:3001"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - NTFY_LISTEN_HTTP=:80
    command: ["serve"]
    volumes:
      - ../ntfy/cache:/var/cache/ntfy
      - ../ntfy/config:/etc/ntfy
    ports:
      - "8080:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

# --- Media stack ---

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ../jellyfin/config:/config
      - ../jellyfin/cache:/cache
      - /srv/media:/media:ro
    ports:
      - "8096:8096"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge
